### ISSUE TITLE
Is the "Run Starsector" config supposed to also load your mod?

### ISSUE THREAD

**Issue by cmcaine** [wispborne/Starsector-IntelliJ-Template#2]
I expected that it would build my mod and enable it in the game, then run the game, but instead it just seems to run the game?

Another strange behaviour is that clicking the "Run" button launches a process that seems to just wait indefinitely without loading the game or terminating, but clicking the debug button makes the game run.

Whatever the expected behaviour is, could we edit the readme to clarify this, thanks!

**Comment by wispborne** [comment]
Thanks, I've added a section for that. It was in the wiki version of this guide but not this one.

The Run button isn't meant to be used. If you want to, you can change `suspend=y` to `suspend-n` in the Run configuration's parameters, or make a new run config for it, or maybe there's a way to use one run config to get both, but frankly I don't see why someone would want to run from IntelliJ without debugging and, if that's needed, they can just run the game normally, so I never spent time investigating the option.

**Comment by cmcaine** [comment]
You're welcome! Just to clarify: clicking the debug button is not supposed to automatically load your mod it just lets you debug starsector, if you want to load your mod you need to copy it from the "out" directory into the starsector mods directory.

**Comment by cmcaine** [comment]
Ah, I see that you explain this in the wiki version too. https://starsector.fandom.com/wiki/IntelliJ_IDEA_Setup#Running_and_debugging

**Comment by wispborne** [comment]
> You're welcome! Just to clarify: clicking the debug button is not supposed to automatically load your mod it just lets you debug starsector, if you want to load your mod you need to copy it from the "out" directory into the starsector mods directory.

True...but it should work if you put the project itself into the mods folder, which is what I do (via symlink). I'll make sure that's mentioned in the readme as well.

**Comment by wispborne** [comment]
It shouldn't create an `out` folder, by the way. It's set up to add the jar to /jars using this:
https://github.com/wispborne/Starsector-IntelliJ-Template/blob/main/.idea/artifacts/Create__jar.xml

**Comment by cmcaine** [comment]
Ah, that makes sense. I was using some of these files with an existing mod, but an edit of Create__jar.xml got it all working for me :)

(Here's the PR I made on Underworld, helped by this template! https://bitbucket.org/modmafia/underworld/pull-requests/5)
